<?xml version="1.0" encoding="UTF-8"?>
<customMapSource>
<name>Queensland Official Aerial Map (May fail depending on token expiry)</name>
<url>https://spatial-img.information.qld.gov.au/arcgis/rest/services/Basemaps/LatestStateProgram_QGovSISPUsers/ImageServer/tile/{$z}/{$y}/{$x}?token=ClsxKN191Q_uab2IJ7XGF5dlmM8upEORMR6eXRxe5bFJ8IaQO3JZ0c4hdWgQqDaYVkpuydkl_d7dBjMs54ROyYzuCTnouqCLeA7_SDiOd3qfya0NdsKideWxKUp82TpUL5RfI3jbXzNkKZy3bbOq464Q2-N8IekEZucvzZuW8R6xFgy107NuVIEyI3NFXwB9</url>
</customMapSource>
